# Generated by Django 2.0.7 on 2018-08-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('deadline', models.DateTimeField()),
                ('details', models.TextField()),
            ],
        ),
    ]
